package org.listeners;

import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;
import lombok.extern.slf4j.Slf4j;
import org.testng.ISuite;
import org.testng.ISuiteListener;
import org.utils.ConfigManager;
import org.utils.ExecutionFootprint;

import static org.api.constants.FrameworkConstants.ALLURE_RESULTS_DIRECTORY;

/**
 * Generates {@code environment.properties} for the Allure report on test suite completion.
 * Reads runtime usage from {@link ExecutionFootprint} instead of static configuration,
 * ensuring the report accurately reflects only the services and devices actually touched.
 */
@Slf4j
public class AllureEnvironmentWriter implements ISuiteListener {

    @Override
    public void onFinish(ISuite suite) {
        try {
            Properties environment = new Properties();
            environment.setProperty("Java", System.getProperty("java.version"));

            if (ExecutionFootprint.wasApiExercised()) {
                environment.setProperty("API.Base.Uri", ConfigManager.getProperty("api.base.uri", "n/a"));
            }

            if (ExecutionFootprint.wasMobileExercised()) {
                environment.setProperty("Platform", ConfigManager.getProperty("platform", "n/a"));
                environment.setProperty("Device", ConfigManager.getProperty("device.name", "n/a"));
                environment.setProperty("App", ConfigManager.getProperty("app.package",
                        ConfigManager.getProperty("app.bundle.id", "n/a")));
                environment.setProperty("Appium.Server", ConfigManager.getProperty("appium.server.url", "n/a"));
            }

            write(environment);

        } catch (Exception e) {
            // Never fail a suite over a report decoration. The report still generates without it.
            log.warn("Could not write the Allure environment file. The report will still generate.", e);
        }
    }

    /**
     * Surefire forwards {@code allure.results.directory} into the test JVM and allure-testng
     * writes its results there. Following the same property keeps this file in the same folder
     * as the results it describes.
     */
    private void write(Properties environment) throws Exception {
        Path resultsDir = Paths.get(System.getProperty(
                "allure.results.directory", ALLURE_RESULTS_DIRECTORY));
        Files.createDirectories(resultsDir);

        try (OutputStream out = Files.newOutputStream(resultsDir.resolve("environment.properties"))) {
            environment.store(out, "Generated by AllureEnvironmentWriter");
        }
    }
}
